version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse:4.0.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set environmental variables
          command: |
            Rscript \
              -e 'dsc = read.dcf("DESCRIPTION")' \
              -e 'cat(sprintf("export PKG_NAME=%s\n", dsc[,"Package"]))' \
              -e 'cat(sprintf("export PKG_VERSION=%s\n", dsc[,"Version"]))' \
              -e 'cat(sprintf("export PKG_TARBALL=%s_%s.tar.gz\n", dsc[,"Package"], dsc[,"Version"]))' \
              >> ${BASH_ENV}

      - run:
          name: Install dependencies
          command: |
            Rscript \
              -e 'repos = BiocManager::repositories("https://hugheylab.github.io/drat/")' \
              -e 'BiocManager::install("annotate")' \
              -e 'devtools::install_dev_deps(dependencies = TRUE, repos = repos, upgrade = TRUE)'

      - run:
          name: nstall CDF packages for vignettes
          command: |
            Rscript \
              -e 'source("R/metapredict_process.R")' \
              -e 'installCustomCdfPackages(c("hgu95av2hsentrezgcdf", "hgu133plus2hsentrezgcdf"))'

      - run:
          name: Download vignette folder
          command: |
            cd vignettes
            wget "https://www.dropbox.com/s/gdrbmn38261dsy7/expression_data.tar.gz?dl=1"
            mv expression_data.tar.gz?dl=1 expression_data.tar.gz
            tar -xf expression_data.tar.gz
            cd ../

      - run:
          name: Build package
          command: R CMD build . --md5

      - run:
          name: Check package
          command: R CMD check ${PKG_TARBALL} --no-manual

      - run:
          name: Check failures
          command: |
            Rscript \
              -e "message(devtools::check_failures(path = '${PKG_NAME}.Rcheck'))" \
              -e "covr::package_coverage()"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: drat-deployment
