on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: check-deploy

jobs:
  check-deploy:
    uses: hugheylab/actions/.github/workflows/check-deploy-metapredict.yaml@main
    secrets: inherit
